- name: Patching and Updating Linux Systems
  hosts: localhost
  connection: local
  become: yes

  tasks:

   - name: Update all host/vm packages
     apt:
       update_cache: true
       cache_valid_time: 3600
       name: "*"
       state: latest

   - name: Upgrade all host/vm packages
     apt:
       upgrade: full
       state: latest
       autoremove: yes

   - name: Install Apt tools for Desktops and Laptops
     apt:
       name:
         - bashtop
         - speedtest-cli
         - curl
         - ansiweather
         - python3-pip
         - weather-util
         - tmux
         - libpam-u2f
         - mosquitto
         - mosquitto-clients
         - duf
         - bat
         - git
         - ncal
         - khal
         - tree
         - mc
         - zsh
         - neofetch
         - yadm
         - nmap
         - gh
         - cmatrix
         - stow
         - ubuntu-advantage-tools
       state: present

  - name: change user shell to zsh 
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh

   - name: Install UV
     shell:
       cmd: curl -LsSf https://astral.sh/uv/install.sh | sh

   - name: Install Starship
     shell:
       cmd: curl -sS https://starship.rs/install.sh | sh -s -- -y | echo 'eval "$(starship init zsh)"' >> $HOME/.zshrc

   - name: Install Oh My ZSH!
     shell:
       cmd: '[ -d "$HOME/.oh-my-zsh" ] || curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh'
